-- Origin Labs styled pricing-sheet catalogue refresh (2026-08-10).
-- Safe to run more than once. Images and admin-managed media are preserved.

UPDATE products SET name='Retatrutide', category='Weight Loss & Metabolic', size_label='10mg / vial', price=100.00, description='The strongest fat-loss peptide available. Curbs hunger, burns stored fat, and balances blood sugar — all at the same time. Think of it as a triple-action version of Ozempic.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Weight management'), use_cases=JSON_ARRAY('weight loss','appetite reduction','hunger control','stored fat use','blood sugar balance'), product_type='research', active=1, sort_order=10 WHERE slug='retatrutide';
UPDATE products SET name='Tirzepatide', category='Weight Loss & Metabolic', size_label='10mg / vial', price=150.00, description='Reduces appetite and helps the body burn fat more efficiently. Works like the active ingredient in Mounjaro. One of the most effective weight-loss compounds studied.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Weight management'), use_cases=JSON_ARRAY('weight loss','appetite reduction','fat metabolism'), product_type='research', active=1, sort_order=11 WHERE slug='tirzepatide';
UPDATE products SET name='Semaglutide', category='Weight Loss & Metabolic', size_label='10mg / vial', price=200.00, description='Tells your brain you''re full so you eat less. Supports steady weight loss and healthier blood sugar. The same mechanism as Ozempic and Wegovy.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Weight management'), use_cases=JSON_ARRAY('satiety','reduced food intake','steady weight loss','blood sugar support'), product_type='research', active=1, sort_order=12 WHERE slug='semaglutide';
UPDATE products SET name='BPC-157', category='Recovery & Healing', size_label='10mg / vial', price=65.00, description='Speeds up healing from injuries — tendons, muscles, gut issues, and inflammation. One of the most studied healing compounds available.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Recovery & healing'), use_cases=JSON_ARRAY('injury recovery','tendon healing','muscle healing','gut support','inflammation support'), product_type='research', active=1, sort_order=20 WHERE slug='bpc-157';
UPDATE products SET name='TB-500', category='Recovery & Healing', size_label='10mg / vial', price=65.00, description='Helps repair muscle tears and soft tissue injuries faster. Reduces stiffness and gets you back to full movement sooner. Works great alongside BPC-157.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Recovery & healing'), use_cases=JSON_ARRAY('muscle tear recovery','soft tissue repair','stiffness reduction','mobility support','recovery'), product_type='research', active=1, sort_order=21 WHERE slug='tb-500';
UPDATE products SET name='Bacteriostatic Water', category='Recovery & Healing', size_label='10ml / vial', price=15.00, description='The sterile water used to mix peptide powders before use. Required for proper preparation.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY(), use_cases=JSON_ARRAY('peptide reconstitution','preparation'), product_type='solution', active=1, sort_order=22 WHERE slug='bacteriostatic-water';
UPDATE products SET name='Wolverine Stack', category='Recovery Stacks — Pre-Mixed Combinations', size_label='20mg / vial', price=130.00, description='The ultimate healing combo. Covers every major recovery pathway — joints, tendons, muscles, and gut.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Recovery & healing'), use_cases=JSON_ARRAY('joint recovery','tendon recovery','muscle recovery','gut support','recovery'), product_type='stack', active=1, sort_order=23 WHERE slug='wolverine-stack';
UPDATE products SET name='KLOW Stack', category='Recovery Stacks — Pre-Mixed Combinations', size_label='80mg / vial', price=125.00, description='Four healing compounds targeting four repair pathways at once: BPC-157 heals tendons, ligaments, and gut lining; TB-500 repairs muscle tears and improves flexibility; GHK-Cu rebuilds collagen, tightens skin, and activates over 1,000 repair genes; KPV directly calms gut and systemic inflammation at the cellular level. The most comprehensive healing stack in the lineup.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Recovery & healing'), use_cases=JSON_ARRAY('tendon repair','ligament repair','gut lining support','muscle recovery','flexibility','collagen support','skin quality','gut inflammation','systemic inflammation'), product_type='stack', active=1, sort_order=24 WHERE slug='klow-stack';
UPDATE products SET name='GLOW Stack', category='Recovery Stacks — Pre-Mixed Combinations', size_label='70mg / vial', price=110.00, description='A three-compound stack focused on skin and deep tissue renewal. Boosts collagen, reduces inflammation, and supports full-body repair. A great starting point before stepping up to KLOW.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Recovery & healing'), use_cases=JSON_ARRAY('skin renewal','deep tissue renewal','collagen support','inflammation support','full-body recovery','skin quality'), product_type='stack', active=1, sort_order=25 WHERE slug='glow-stack';
UPDATE products SET name='Tesamorelin', category='Growth Hormone & Body Composition', size_label='10mg / vial', price=60.00, description='Tells your body to produce more of its own growth hormone naturally. Helps reduce belly fat, build lean muscle, and sharpen mental focus.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Weight management','Performance'), use_cases=JSON_ARRAY('growth hormone support','belly fat reduction','lean muscle','mental focus','body composition'), product_type='research', active=1, sort_order=30 WHERE slug='tesamorelin';
UPDATE products SET name='Ipamorelin', category='Growth Hormone & Body Composition', size_label='10mg / vial', price=60.00, description='Triggers a clean burst of growth hormone with no unwanted side effects. Supports better sleep, lean muscle, and stronger bones.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Performance'), use_cases=JSON_ARRAY('growth hormone support','better sleep','sleep quality','lean muscle','bone strength','body composition'), product_type='research', active=1, sort_order=31 WHERE slug='ipamorelin';
UPDATE products SET name='CJC-1295 + Ipamorelin', category='Growth Hormone & Body Composition', size_label='10mg / vial', price=115.00, description='Two growth hormone boosters that work together for a stronger, longer-lasting effect than either alone. A popular combination for body composition and recovery.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Performance'), use_cases=JSON_ARRAY('growth hormone support','body composition','recovery'), product_type='stack', active=1, sort_order=32 WHERE slug='cjc-1295-ipamorelin';
UPDATE products SET name='Epithalon', category='Anti-Aging & Longevity', size_label='50mg / vial', price=65.00, description='Studied for slowing cellular aging. Works by protecting the ends of your DNA — the same structures that shorten as we get older. Also supports better sleep through melatonin regulation.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Longevity'), use_cases=JSON_ARRAY('cellular aging','dna protection','better sleep','sleep support','melatonin regulation','longevity'), product_type='research', active=1, sort_order=40 WHERE slug='epithalon';
UPDATE products SET name='GHK-Cu', category='Anti-Aging & Longevity', size_label='100mg / vial', price=60.00, description='A copper peptide that rebuilds collagen, tightens skin, speeds wound healing, and stimulates hair growth. Naturally declines with age — one of the most researched anti-aging compounds.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Longevity'), use_cases=JSON_ARRAY('collagen support','skin tightening','wound healing','hair growth','anti-aging','skin quality'), product_type='research', active=1, sort_order=41 WHERE slug='ghk-cu';
UPDATE products SET name='MOTS-c', category='Anti-Aging & Longevity', size_label='40mg / vial', price=95.00, description='Supports energy production at the cellular level. Helps the body respond better to insulin and handle physical stress. Produced naturally inside your mitochondria.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Energy','Performance'), use_cases=JSON_ARRAY('cellular energy','energy production','insulin response','physical stress response','mitochondrial energy'), product_type='research', active=1, sort_order=42 WHERE slug='ots-c-mots-c';
UPDATE products SET name='NAD+', category='Anti-Aging & Longevity', size_label='1000mg / vial', price=95.00, description='The energy molecule your cells run on — and it drops by half by middle age. Restoring it supports mental clarity, DNA repair, and overall cellular health.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Energy','Longevity'), use_cases=JSON_ARRAY('cellular energy','mental clarity','dna repair','cellular health','longevity'), product_type='research', active=1, sort_order=43 WHERE slug='nad-plus';
UPDATE products SET name='Semax', category='Brain & Focus', size_label='10mg / vial', price=55.00, description='Sharpens focus, improves memory, and protects brain cells. Works by boosting the brain''s own growth factor (BDNF). Originally developed for cognitive enhancement and stroke recovery.', usage_notice='FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION', goal_tags=JSON_ARRAY('Performance'), use_cases=JSON_ARRAY('focus','memory','brain cell protection','cognitive enhancement','stroke recovery research'), product_type='research', active=1, sort_order=50 WHERE slug='semax';
