CREATE TABLE IF NOT EXISTS body_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  assessment_token CHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  order_id BIGINT UNSIGNED NULL,
  front_path VARCHAR(500) NULL,
  side_path VARCHAR(500) NULL,
  back_path VARCHAR(500) NULL,
  visual_summary TEXT NULL,
  visible_signals JSON NULL,
  goal_tags JSON NULL,
  analysis_json JSON NULL,
  confidence ENUM('low','medium','high') NOT NULL DEFAULT 'low',
  ai_model VARCHAR(120) NULL,
  status ENUM('created','uploaded','review_pending','approved','excluded','deleted') NOT NULL DEFAULT 'created',
  consent_at DATETIME NOT NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_body_profile_token (assessment_token),
  KEY idx_body_profile_user (user_id),
  KEY idx_body_profile_order (order_id),
  KEY idx_body_profile_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
