SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(120) NOT NULL,
  name VARCHAR(190) NOT NULL,
  category VARCHAR(120) NOT NULL,
  size_label VARCHAR(120) NOT NULL DEFAULT '',
  price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  standalone_price DECIMAL(10,2) NULL,
  billing_interval ENUM('one_time','month') NOT NULL DEFAULT 'month',
  tags JSON NULL,
  description TEXT NULL,
  compound VARCHAR(255) NULL,
  usage_notice VARCHAR(255) NULL,
  goal_tags JSON NULL,
  use_cases JSON NULL,
  product_type ENUM('checkout','research','stack','service','solution','medication','vitamin') NOT NULL DEFAULT 'research',
  active TINYINT(1) NOT NULL DEFAULT 1,
  medication VARCHAR(190) NULL,
  dosage VARCHAR(190) NULL,
  image_url VARCHAR(500) NULL,
  image_alt VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 100,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_products_slug (slug),
  KEY idx_products_active_sort (active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_settings (
  id TINYINT UNSIGNED NOT NULL DEFAULT 1,
  brand_name VARCHAR(190) NOT NULL DEFAULT 'Thrivel IQ',
  tagline VARCHAR(255) NULL,
  logo_dark_url VARCHAR(500) NULL,
  logo_light_url VARCHAR(500) NULL,
  favicon_url VARCHAR(500) NULL,
  hero_image_url VARCHAR(500) NULL,
  auth_image_url VARCHAR(500) NULL,
  checkout_image_url VARCHAR(500) NULL,
  dashboard_image_url VARCHAR(500) NULL,
  assessment_image_url VARCHAR(500) NULL,
  default_product_image_url VARCHAR(500) NULL,
  primary_color VARCHAR(20) NOT NULL DEFAULT '#7AC7C8',
  gradient_mid_color VARCHAR(20) NOT NULL DEFAULT '#9971B1',
  secondary_color VARCHAR(20) NOT NULL DEFAULT '#EC437D',
  accent_color VARCHAR(20) NOT NULL DEFAULT '#F4946E',
  background_color VARCHAR(20) NOT NULL DEFAULT '#0A1133',
  panel_color VARCHAR(20) NOT NULL DEFAULT '#101943',
  support_email VARCHAR(190) NULL,
  footer_text VARCHAR(255) NULL,
  login_headline VARCHAR(255) NULL,
  login_subheadline TEXT NULL,
  login_title VARCHAR(190) NULL,
  login_description VARCHAR(255) NULL,
  signup_headline VARCHAR(255) NULL,
  signup_subheadline TEXT NULL,
  signup_title VARCHAR(190) NULL,
  signup_description VARCHAR(255) NULL,
  account_title VARCHAR(190) NULL,
  account_description VARCHAR(255) NULL,
  checkout_title VARCHAR(255) NULL,
  checkout_description TEXT NULL,
  dashboard_title VARCHAR(255) NULL,
  dashboard_description TEXT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS media (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  file_name VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  url VARCHAR(500) NOT NULL,
  alt_text VARCHAR(255) NULL,
  size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_media_file_name (file_name),
  KEY idx_media_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(190) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  country VARCHAR(100) NULL,
  state VARCHAR(100) NULL,
  phone VARCHAR(40) NULL,
  role ENUM('customer','reviewer','admin') NOT NULL DEFAULT 'customer',
  verified TINYINT(1) NOT NULL DEFAULT 1,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  deactivated_at DATETIME NULL,
  deactivated_by BIGINT UNSIGNED NULL,
  plan_updates TINYINT(1) NOT NULL DEFAULT 1,
  reviewer_messages TINYINT(1) NOT NULL DEFAULT 1,
  marketing_emails TINYINT(1) NOT NULL DEFAULT 0,
  api_token_hash CHAR(64) NULL,
  api_token_expires_at DATETIME NULL,
  last_login_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email),
  UNIQUE KEY uq_users_api_token_hash (api_token_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS staff_audit_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  actor_user_id BIGINT UNSIGNED NULL,
  actor_name VARCHAR(190) NOT NULL DEFAULT '',
  target_user_id BIGINT UNSIGNED NULL,
  target_name VARCHAR(190) NOT NULL DEFAULT '',
  target_email VARCHAR(190) NOT NULL DEFAULT '',
  action VARCHAR(80) NOT NULL,
  from_role VARCHAR(40) NULL,
  to_role VARCHAR(40) NULL,
  note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staff_audit_target (target_user_id, created_at),
  KEY idx_staff_audit_actor (actor_user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_token VARCHAR(100) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  email VARCHAR(190) NULL,
  first_name VARCHAR(100) NULL,
  last_name VARCHAR(100) NULL,
  stack_product_id BIGINT UNSIGNED NULL,
  stack_name VARCHAR(190) NULL,
  stack_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  product_subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  advisor_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  payment_status ENUM('pending','paid','failed','refunded') NOT NULL DEFAULT 'pending',
  payment_reference VARCHAR(190) NULL,
  assessment_json JSON NULL,
  items_json JSON NULL,
  shipping_address_json JSON NULL,
  advisor_billing_cycle ENUM('month','year') NOT NULL DEFAULT 'month',
  account_created_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_orders_token (order_token),
  KEY idx_orders_email (email),
  KEY idx_orders_payment_status (payment_status),
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_stack_product FOREIGN KEY (stack_product_id) REFERENCES products(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  goal VARCHAR(190) NOT NULL,
  medication VARCHAR(190) NULL,
  dosage VARCHAR(190) NULL,
  package_name VARCHAR(190) NULL,
  workout_plan JSON NULL,
  meal_plan JSON NULL,
  vitamins JSON NULL,
  weekly_targets JSON NULL,
  reviewer_note TEXT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'needs_review',
  focus TEXT NULL,
  nutrition TEXT NULL,
  activity TEXT NULL,
  sleep TEXT NULL,
  recovery TEXT NULL,
  milestones JSON NULL,
  categories JSON NULL,
  product_ids JSON NULL,
  flags JSON NULL,
  reviewer VARCHAR(190) NULL,
  reviewer_user_id BIGINT UNSIGNED NULL,
  reviewer_assigned_at DATETIME NULL,
  internal_reviewer_note TEXT NULL,
  requested_information TEXT NULL,
  member_response TEXT NULL,
  member_response_at DATETIME NULL,
  next_check_in DATETIME NULL,
  version INT NOT NULL DEFAULT 1,
  reviewer_approved_at DATETIME NULL,
  released_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_member_plans_user (user_id),
  KEY idx_member_plans_status (status),
  CONSTRAINT fk_member_plans_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS plan_review_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  plan_id BIGINT UNSIGNED NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  actor_name VARCHAR(190) NOT NULL DEFAULT '',
  actor_role VARCHAR(40) NOT NULL DEFAULT '',
  action VARCHAR(80) NOT NULL,
  from_status VARCHAR(50) NULL,
  to_status VARCHAR(50) NULL,
  note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_review_events_plan_created (plan_id, created_at),
  CONSTRAINT fk_review_events_plan FOREIGN KEY (plan_id) REFERENCES member_plans(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_plan_progress (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  plan_id BIGINT UNSIGNED NOT NULL,
  item_type ENUM('weekly_target','workout') NOT NULL,
  item_key CHAR(64) NOT NULL,
  item_text VARCHAR(500) NOT NULL,
  period_start DATE NOT NULL,
  completed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_member_progress_period_item (user_id,plan_id,item_type,item_key,period_start),
  KEY idx_member_progress_plan_period (plan_id,period_start),
  CONSTRAINT fk_member_progress_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_member_progress_plan FOREIGN KEY (plan_id) REFERENCES member_plans(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_weight_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  weight_lbs DECIMAL(7,2) NOT NULL,
  logged_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_weight_user_logged (user_id,logged_at),
  CONSTRAINT fk_weight_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_checkins (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  plan_id BIGINT UNSIGNED NULL,
  energy_score TINYINT UNSIGNED NULL,
  adherence_score TINYINT UNSIGNED NULL,
  sleep_hours DECIMAL(4,1) NULL,
  note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_checkin_user_created (user_id,created_at),
  KEY idx_checkin_plan_created (plan_id,created_at),
  CONSTRAINT fk_checkin_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_checkin_plan FOREIGN KEY (plan_id) REFERENCES member_plans(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_nutrition_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  protein_grams DECIMAL(7,1) NOT NULL DEFAULT 0,
  carbs_grams DECIMAL(7,1) NOT NULL DEFAULT 0,
  hydration_oz DECIMAL(7,1) NOT NULL DEFAULT 0,
  logged_on DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_member_nutrition_day (user_id,logged_on),
  KEY idx_member_nutrition_user_day (user_id,logged_on),
  CONSTRAINT fk_member_nutrition_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS advisor_subscriptions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  source_order_id BIGINT UNSIGNED NULL,
  product_slug VARCHAR(120) NOT NULL DEFAULT 'ai-health-advisor',
  status ENUM('active','past_due','cancel_at_period_end','cancelled') NOT NULL DEFAULT 'active',
  monthly_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  billing_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  billing_cycle ENUM('month','year') NOT NULL DEFAULT 'month',
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  current_period_start DATETIME NOT NULL,
  current_period_end DATETIME NOT NULL,
  cancel_at_period_end TINYINT(1) NOT NULL DEFAULT 0,
  payment_provider VARCHAR(50) NOT NULL DEFAULT 'prototype',
  provider_subscription_id VARCHAR(190) NULL,
  cancelled_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_advisor_subscription_user (user_id),
  KEY idx_advisor_subscription_status (status),
  CONSTRAINT fk_advisor_subscription_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_advisor_subscription_order FOREIGN KEY (source_order_id) REFERENCES orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS advisor_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  role ENUM('user','assistant') NOT NULL,
  content TEXT NOT NULL,
  model VARCHAR(120) NULL,
  response_id VARCHAR(190) NULL,
  safety_class VARCHAR(60) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_advisor_messages_user_created (user_id, created_at, id),
  CONSTRAINT fk_advisor_messages_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;

-- Optional private body-profile images captured during assessment.
CREATE TABLE IF NOT EXISTS body_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  assessment_token CHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  order_id BIGINT UNSIGNED NULL,
  front_path VARCHAR(500) NULL,
  side_path VARCHAR(500) NULL,
  back_path VARCHAR(500) NULL,
  visual_summary TEXT NULL,
  visible_signals JSON NULL,
  goal_tags JSON NULL,
  analysis_json JSON NULL,
  confidence ENUM('low','medium','high') NOT NULL DEFAULT 'low',
  ai_model VARCHAR(120) NULL,
  status ENUM('created','uploaded','review_pending','approved','excluded','deleted') NOT NULL DEFAULT 'created',
  consent_at DATETIME NOT NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_body_profile_token (assessment_token),
  KEY idx_body_profile_user (user_id),
  KEY idx_body_profile_order (order_id),
  KEY idx_body_profile_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
