INSERT INTO site_settings (
  id,brand_name,tagline,logo_dark_url,logo_light_url,favicon_url,hero_image_url,auth_image_url,
  checkout_image_url,dashboard_image_url,assessment_image_url,default_product_image_url,
  primary_color,gradient_mid_color,secondary_color,accent_color,background_color,panel_color,support_email,footer_text,
  login_headline,login_subheadline,login_title,login_description,
  signup_headline,signup_subheadline,signup_title,signup_description,
  account_title,account_description,checkout_title,checkout_description,dashboard_title,dashboard_description
) VALUES (
  1,'Thrivel IQ','Private, personalized, expert-reviewed wellness guidance.',
  '/uploads/defaults/logo-dark.svg','/uploads/defaults/logo-light.svg','/uploads/defaults/favicon.svg',
  '/uploads/defaults/hero-wellness.svg','/uploads/defaults/auth-wellness.svg','/uploads/defaults/checkout-stack.svg',
  '/uploads/defaults/dashboard-progress.svg','/uploads/defaults/assessment-wellness.svg','/uploads/defaults/product-default.svg',
  '#7AC7C8','#9971B1','#EC437D','#F4946E','#0A1133','#101943','support@thriveliq.com','Private, secure, and expert-reviewed.',
  'Welcome back to your personalized health dashboard',
  'Continue your plan, review your recommendations and track your progress.',
  'Log in','Use the email and password created after checkout.',
  'Start your personalized wellness plan',
  'Complete the assessment and checkout before creating your account.',
  'Create your account after payment','Your assessment, purchase and plan are linked during account creation.',
  'Create your member account','This account will own your assessment, order and wellness plan.',
  'Choose your stack and advisor access',
  'Select a package or continue with advisor-only access. Account creation follows payment.',
  'Your wellness dashboard',
  'Your goal, plan, purchased package and reviewer-controlled details are shown here.'
) ON DUPLICATE KEY UPDATE id=VALUES(id);

INSERT INTO media (file_name,original_name,mime_type,url,alt_text,size_bytes) VALUES
('default-logo-dark.svg','logo-dark.svg','image/svg+xml','/uploads/defaults/logo-dark.svg','Thrivel IQ logo for dark backgrounds',0),
('default-logo-light.svg','logo-light.svg','image/svg+xml','/uploads/defaults/logo-light.svg','Thrivel IQ logo for light backgrounds',0),
('default-favicon.svg','favicon.svg','image/svg+xml','/uploads/defaults/favicon.svg','Thrivel IQ favicon',0),
('default-hero-wellness.svg','hero-wellness.svg','image/svg+xml','/uploads/defaults/hero-wellness.svg','Personalized wellness dashboard illustration',0),
('default-auth-wellness.svg','auth-wellness.svg','image/svg+xml','/uploads/defaults/auth-wellness.svg','Secure member access illustration',0),
('default-checkout-stack.svg','checkout-stack.svg','image/svg+xml','/uploads/defaults/checkout-stack.svg','Wellness stack checkout illustration',0),
('default-dashboard-progress.svg','dashboard-progress.svg','image/svg+xml','/uploads/defaults/dashboard-progress.svg','Wellness progress banner',0),
('default-assessment-wellness.svg','assessment-wellness.svg','image/svg+xml','/uploads/defaults/assessment-wellness.svg','Health assessment illustration',0),
('default-product.svg','product-default.svg','image/svg+xml','/uploads/defaults/product-default.svg','Thrivel IQ wellness product',0),
('default-product-weightloss.svg','product-weightloss.svg','image/svg+xml','/uploads/defaults/product-weightloss.svg','Weightloss Stack',0),
('default-product-recovery.svg','product-recovery.svg','image/svg+xml','/uploads/defaults/product-recovery.svg','Recovery Stack',0),
('default-product-advisor.svg','product-advisor.svg','image/svg+xml','/uploads/defaults/product-advisor.svg','Health Advisor access',0)
ON DUPLICATE KEY UPDATE original_name=VALUES(original_name), mime_type=VALUES(mime_type), url=VALUES(url), alt_text=VALUES(alt_text);

DELETE FROM products WHERE slug IN ('sema','tirz','reta','bpc','tb500','bpc-tb-stack','vitamin-d3','magnesium','ghkcu','ta1','glow','tesa','ipa','cjc-ipa','motsc','nad');

INSERT INTO products (
  slug,name,category,size_label,price,standalone_price,description,compound,usage_notice,goal_tags,use_cases,
  product_type,active,medication,dosage,image_url,image_alt,sort_order
) VALUES
('weightloss-stack','Weightloss Stack','Checkout Packages','Monthly plan',210.00,NULL,'A reviewer-configured weight management package. The final product selection is confirmed after assessment review.','','Platform checkout package. Individual research products remain labeled for research use only.',JSON_ARRAY('weight loss','metabolic'),JSON_ARRAY('weight management','appetite support','metabolic support'),'checkout',1,'Reviewer selected','Reviewer assigned','/uploads/defaults/product-weightloss.svg','Weightloss Stack',1),
('recovery-stack','Recovery Stack','Checkout Packages','Monthly plan',190.00,NULL,'A reviewer-configured recovery package based on training load, soreness, and recovery goals.','','Platform checkout package. Individual research products remain labeled for research use only.',JSON_ARRAY('recovery','healing'),JSON_ARRAY('recovery','healing','muscle recovery','tissue repair'),'checkout',1,'Reviewer selected','Reviewer assigned','/uploads/defaults/product-recovery.svg','Recovery Stack',2),
('ai-health-advisor','AI Health Coach','Services','Monthly or annual subscription',19.99,19.99,'Private AI wellness advisor chat personalized to the member assessment, purchased products and reviewer-published plan. Restricted to health and Thrivel IQ topics.','','AI wellness guidance. Medication and dosage remain reviewer-controlled. Research-use products are not recommended for human or animal use.',JSON_ARRAY('advisor'),JSON_ARRAY('wellness guidance','workout planning','meal planning','sleep support','recovery guidance','reviewer plan explanations'),'service',1,'','','/uploads/defaults/product-advisor.svg','AI Health Coach',3),
('retatrutide','Retatrutide','Weight Loss & Metabolic','10mg / vial',100.00,NULL,'The strongest fat-loss peptide available. Curbs hunger, burns stored fat, and balances blood sugar — all at the same time. Think of it as a triple-action version of Ozempic.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Weight management'),JSON_ARRAY('weight loss','appetite reduction','hunger control','stored fat use','blood sugar balance'),'research',1,'','', '/uploads/defaults/product-default.svg','Retatrutide',10),
('tirzepatide','Tirzepatide','Weight Loss & Metabolic','10mg / vial',150.00,NULL,'Reduces appetite and helps the body burn fat more efficiently. Works like the active ingredient in Mounjaro. One of the most effective weight-loss compounds studied.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Weight management'),JSON_ARRAY('weight loss','appetite reduction','fat metabolism'),'research',1,'','', '/uploads/defaults/product-default.svg','Tirzepatide',11),
('semaglutide','Semaglutide','Weight Loss & Metabolic','10mg / vial',200.00,NULL,'Tells your brain you''re full so you eat less. Supports steady weight loss and healthier blood sugar. The same mechanism as Ozempic and Wegovy.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Weight management'),JSON_ARRAY('satiety','reduced food intake','steady weight loss','blood sugar support'),'research',1,'','', '/uploads/defaults/product-default.svg','Semaglutide',12),
('bpc-157','BPC-157','Recovery & Healing','10mg / vial',65.00,NULL,'Speeds up healing from injuries — tendons, muscles, gut issues, and inflammation. One of the most studied healing compounds available.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Recovery & healing'),JSON_ARRAY('injury recovery','tendon healing','muscle healing','gut support','inflammation support'),'research',1,'','', '/uploads/defaults/product-default.svg','BPC-157',20),
('tb-500','TB-500','Recovery & Healing','10mg / vial',65.00,NULL,'Helps repair muscle tears and soft tissue injuries faster. Reduces stiffness and gets you back to full movement sooner. Works great alongside BPC-157.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Recovery & healing'),JSON_ARRAY('muscle tear recovery','soft tissue repair','stiffness reduction','mobility support','recovery'),'research',1,'','', '/uploads/defaults/product-default.svg','TB-500',21),
('bacteriostatic-water','Bacteriostatic Water','Recovery & Healing','10ml / vial',15.00,NULL,'The sterile water used to mix peptide powders before use. Required for proper preparation.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY(),JSON_ARRAY('peptide reconstitution','preparation'),'solution',1,'','', '/uploads/defaults/product-default.svg','Bacteriostatic Water',22),
('wolverine-stack','Wolverine Stack','Recovery Stacks — Pre-Mixed Combinations','20mg / vial',130.00,NULL,'The ultimate healing combo. Covers every major recovery pathway — joints, tendons, muscles, and gut.','BPC-157 + TB-500','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Recovery & healing'),JSON_ARRAY('joint recovery','tendon recovery','muscle recovery','gut support','recovery'),'stack',1,'','', '/uploads/defaults/product-default.svg','Wolverine Stack',23),
('klow-stack','KLOW Stack','Recovery Stacks — Pre-Mixed Combinations','80mg / vial',125.00,NULL,'Four healing compounds targeting four repair pathways at once: BPC-157 heals tendons, ligaments, and gut lining; TB-500 repairs muscle tears and improves flexibility; GHK-Cu rebuilds collagen, tightens skin, and activates over 1,000 repair genes; KPV directly calms gut and systemic inflammation at the cellular level. The most comprehensive healing stack in the lineup.','BPC-157 + GHK-Cu + TB-500 + KPV','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Recovery & healing'),JSON_ARRAY('tendon repair','ligament repair','gut lining support','muscle recovery','flexibility','collagen support','skin quality','gut inflammation','systemic inflammation'),'stack',1,'','', '/uploads/defaults/product-default.svg','KLOW Stack',24),
('glow-stack','GLOW Stack','Recovery Stacks — Pre-Mixed Combinations','70mg / vial',110.00,NULL,'A three-compound stack focused on skin and deep tissue renewal. Boosts collagen, reduces inflammation, and supports full-body repair. A great starting point before stepping up to KLOW.','BPC-157 + GHK-Cu + TB-500','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Recovery & healing'),JSON_ARRAY('skin renewal','deep tissue renewal','collagen support','inflammation support','full-body recovery','skin quality'),'stack',1,'','', '/uploads/defaults/product-default.svg','GLOW Stack',25),
('tesamorelin','Tesamorelin','Growth Hormone & Body Composition','10mg / vial',60.00,NULL,'Tells your body to produce more of its own growth hormone naturally. Helps reduce belly fat, build lean muscle, and sharpen mental focus.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Weight management','Performance'),JSON_ARRAY('growth hormone support','belly fat reduction','lean muscle','mental focus','body composition'),'research',1,'','', '/uploads/defaults/product-default.svg','Tesamorelin',30),
('ipamorelin','Ipamorelin','Growth Hormone & Body Composition','10mg / vial',60.00,NULL,'Triggers a clean burst of growth hormone with no unwanted side effects. Supports better sleep, lean muscle, and stronger bones.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Performance'),JSON_ARRAY('growth hormone support','better sleep','sleep quality','lean muscle','bone strength','body composition'),'research',1,'','', '/uploads/defaults/product-default.svg','Ipamorelin',31),
('cjc-1295-ipamorelin','CJC-1295 + Ipamorelin','Growth Hormone & Body Composition','10mg / vial',115.00,NULL,'Two growth hormone boosters that work together for a stronger, longer-lasting effect than either alone. A popular combination for body composition and recovery.','CJC No DAC 5mg + Ipamorelin 5mg','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Performance'),JSON_ARRAY('growth hormone support','body composition','recovery'),'stack',1,'','', '/uploads/defaults/product-default.svg','CJC-1295 + Ipamorelin',32),
('epithalon','Epithalon','Anti-Aging & Longevity','50mg / vial',65.00,NULL,'Studied for slowing cellular aging. Works by protecting the ends of your DNA — the same structures that shorten as we get older. Also supports better sleep through melatonin regulation.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Longevity'),JSON_ARRAY('cellular aging','dna protection','better sleep','sleep support','melatonin regulation','longevity'),'research',1,'','', '/uploads/defaults/product-default.svg','Epithalon',40),
('ghk-cu','GHK-Cu','Anti-Aging & Longevity','100mg / vial',60.00,NULL,'A copper peptide that rebuilds collagen, tightens skin, speeds wound healing, and stimulates hair growth. Naturally declines with age — one of the most researched anti-aging compounds.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Longevity'),JSON_ARRAY('collagen support','skin tightening','wound healing','hair growth','anti-aging','skin quality'),'research',1,'','', '/uploads/defaults/product-default.svg','GHK-Cu',41),
('ots-c-mots-c','MOTS-c','Anti-Aging & Longevity','40mg / vial',95.00,NULL,'Supports energy production at the cellular level. Helps the body respond better to insulin and handle physical stress. Produced naturally inside your mitochondria.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Energy','Performance'),JSON_ARRAY('cellular energy','energy production','insulin response','physical stress response','mitochondrial energy'),'research',1,'','', '/uploads/defaults/product-default.svg','MOTS-c',42),
('nad-plus','NAD+','Anti-Aging & Longevity','1000mg / vial',95.00,NULL,'The energy molecule your cells run on — and it drops by half by middle age. Restoring it supports mental clarity, DNA repair, and overall cellular health.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Energy','Longevity'),JSON_ARRAY('cellular energy','mental clarity','dna repair','cellular health','longevity'),'research',1,'','', '/uploads/defaults/product-default.svg','NAD+',43),
('semax','Semax','Brain & Focus','10mg / vial',55.00,NULL,'Sharpens focus, improves memory, and protects brain cells. Works by boosting the brain''s own growth factor (BDNF). Originally developed for cognitive enhancement and stroke recovery.','','FOR RESEARCH USE ONLY - NOT FOR HUMAN OR ANIMAL CONSUMPTION',JSON_ARRAY('Performance'),JSON_ARRAY('focus','memory','brain cell protection','cognitive enhancement','stroke recovery research'),'research',1,'','', '/uploads/defaults/product-default.svg','Semax',50)
ON DUPLICATE KEY UPDATE
name=VALUES(name), category=VALUES(category), size_label=VALUES(size_label), price=VALUES(price),
standalone_price=VALUES(standalone_price), description=VALUES(description), compound=VALUES(compound),
usage_notice=VALUES(usage_notice), goal_tags=VALUES(goal_tags), use_cases=VALUES(use_cases), product_type=VALUES(product_type),
active=VALUES(active), medication=VALUES(medication), dosage=VALUES(dosage), image_url=VALUES(image_url),
image_alt=VALUES(image_alt), sort_order=VALUES(sort_order);
